<a href="https://colab.research.google.com/github/Riturajkumari/Machine_learning/blob/main/Pearson_Correlaton_coff_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1. Pearson correlation coefficient is a measure of the linear relationship between two variables. Suppose
you have collected data on the amount of time students spend studying for an exam and their final exam
scores. Calculate the Pearson correlation coefficient between these two variables and interpret the result.**

**Correlation coefficients are used to measure how strong a relationship is between two variables.**

The Pearson’s correlation coefficient is denoted with the symbol “R”. The correlation coefficient formula returns a value between 1 and -1. Here,

- -1 indicates a strong negative relationship
- 1 indicates strong positive relationships
- And a result of zero indicates no relationship at all

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df= sns.load_dataset('healthexp')
df.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [ ]:
##covariance
df.cov()

                         Year  Spending_USD  Life_Expectancy
Year               201.098848  2.571883e+04        41.915454
Spending_USD     25718.827373  4.817761e+06      4166.800912
Life_Expectancy     41.915454  4.166801e+03        10.733902

In [ ]:
##Pearson correlation coefficient

df.corr(method='pearson')

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.826273         0.902175
Spending_USD     0.826273      1.000000         0.579430
Life_Expectancy  0.902175      0.579430         1.000000

**Q2. Spearman's rank correlation is a measure of the monotonic relationship between two variables.
Suppose you have collected data on the amount of sleep individuals get each night and their overall job
satisfaction level on a scale of 1 to 10. Calculate the Spearman's rank correlation between these two
variables and interpret the result.**

In [ ]:
import pandas as pd
data= pd.DataFrame({
    'amount':[200,300,400,500,600,700,800,850,900,950],
    'jov_scale_levl':[1,2,3,4,5,6,7,8,9,10]
})

In [ ]:
##spearman rank correlation
data.corr(method='spearman')

                amount  jov_scale_levl
amount             1.0             1.0
jov_scale_levl     1.0             1.0

**Q3. Suppose you are conducting a study to examine the relationship between the number of hours of
exercise per week and body mass index (BMI) in a sample of adults. You collected data on both variables
for 50 participants. Calculate the Pearson correlation coefficient and the Spearman's rank correlation
between these two variables and compare the results.**

In [ ]:
data=pd.DataFrame({'num_of_hour':[2,4,5,6,3,7,8],
'mass':[45,55,56,67,64,56,59]
})

In [ ]:
##spearman rank correlation
data.corr(method='spearman')

             num_of_hour     mass
num_of_hour      1.00000  0.43245
mass             0.43245  1.00000

**Q4. A researcher is interested in examining the relationship between the number of hours individuals
spend watching television per day and their level of physical activity. The researcher collected data on
both variables from a sample of 50 participants. Calculate the Pearson correlation coefficient between
these two variables.**

In [ ]:
df=pd.DataFrame({'num_of_hour':[2,3,5,7,8,9,10],
 'level_physical_activity':[3,4,2,5,6,1,3]
})

In [ ]:
#  Pearson correlation coefficient between these two variables.
##Pearson correlation coefficient

df.corr(method='pearson')

                         num_of_hour  level_physical_activity
num_of_hour                 1.000000                -0.027354
level_physical_activity    -0.027354                 1.000000

**Q5. A survey was conducted to examine the relationship between age and preference for a particular
brand of soft drink. The survey results are shown below:**

In [ ]:
df= pd.DataFrame({
    'age':[25,42,37,19,31,28],
    'soft_drink_priference':['cock','pepsi','mountain due','coke','pepsi','cock']
})

In [ ]:
df

   age soft_drink_priference
0   25                  cock
1   42                 pepsi
2   37          mountain due
3   19                  coke
4   31                 pepsi
5   28                  cock

In [ ]:
df['soft_drink_priference'].value_counts()

cock            2
pepsi           2
mountain due    1
coke            1
Name: soft_drink_priference, dtype: int64

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
encoder=OneHotEncoder()

In [ ]:
encoder.fit_transform(df[['soft_drink_priference']]).toarray()

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [ ]:
pd.DataFrame(encoder.fit_transform(df[['soft_drink_priference']]).toarray(),columns=encoder.get_feature_names_out())

,soft_drink_priference_cock,soft_drink_priference_coke,soft_drink_priference_mountain due,soft_drink_priference_pepsi
0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0
2,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,1.0
5,1.0,0.0,0.0,0.0

In [ ]:
#  Pearson correlation coefficient between these two variables.
##Pearson correlation coefficient

df.corr(method='pearson')

     age
age  1.0

**Q6. A company is interested in examining the relationship between the number of sales calls made per day
and the number of sales made per week. The company collected data on both variables from a sample of
30 sales representatives. Calculate the Pearson correlation coefficient between these two variables.**

In [ ]:
df= pd.DataFrame({
    'number_of_sale':[20,23,24,25,26,30],
    'num_of_sale_per_week':[100,120,130,150,160,180]
})

In [ ]:
#  Pearson correlation coefficient between these two variables.
##Pearson correlation coefficient

df.corr(method='pearson')

                      number_of_sale  num_of_sale_per_week
number_of_sale              1.000000              0.974944
num_of_sale_per_week        0.974944              1.000000